### ISSUE TITLE
Consider reporting component PSNR separately

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [thorfdbg/difftest_ng#1]
Great software!  Have you considered an option to report the component PSNRs separately?  Users are often more concerned about the Y PSNR than the Cb/Cr PSNR, for example.

**Comment by thorfdbg** [comment]
Thanks for the flowers. difftest is actually the workhorse software of ISO SC29WG1 aka JPEG, so we found quite a lot of good news for it.

Concerning your issue, you can already do that. While the architecture only allows to provide one output per "meter", one can combine several meters on the command line. The following command line will do the requested job, provided input images are in yuv:

difftest_ng --only 0 --psnr --restore --only 1 --psnr --restore --only 2 --psnr input.yuv output.yuv

A small alias or a batch script may make this easier to type.

Hope this helps.
