### ISSUE TITLE
How to convert PFM to DPX that is float with all RGB components?

### ISSUE THREAD

**Issue by richardpl** [thorfdbg/difftest_ng#2]
It would be best if some examples of commands are provided in documentation.

**Comment by thorfdbg** [comment]
difftest_ng always requires two (regular) arguments, the two images to compare to. If you only want to run it for conversion, the second image can be suppressed by "-". Conversion is triggered by "--convert target". Thus, to convert pfm to dpx, use:

difftest_ng --convert out.dpx in.pfm -

Please don't forget the terminating minus sign saying that there is no second image to compare to.

**Comment by richardpl** [comment]
Hmm, but this somehow always create single component DPX image.

**Comment by thorfdbg** [comment]
Not that I know of:

> difftest_ng --convert out.dpx /store/pics/xt_float/WillyDesk.exr.pfm -
> difftest_ng --depth out.dpx -
Depth:  3

But then again, dpx is largely underspecified, and I haven't had much testing done with floating point input. How do you test the output dpx, and can you work out what this tool exactly expects?

**Comment by thorfdbg** [comment]
As an additional idea, there are several "dialects" of dpx. "separate" and "interleaved". You may want to try them as well. Not all dpx readers understand all dialects, i.e.

difftest_ng --separate --convert out.dpx /store/pics/xt_float/WillyDesk.exr.pfm -

**Comment by richardpl** [comment]
Thanks! --interleaved did it!

I just work on libavcodec implementation of dpx decoder, and come here after finding out that ImageMagick produces garbage DPX with supposed 32bit depth floats.
My code works just fine with output of this tool.

**Comment by thorfdbg** [comment]
As the result works, closing this issue now (after a long time).
